quarkus.http.port=${PORT:8080}

# Banco de dados Oracle
quarkus.datasource.db-kind=oracle
quarkus.datasource.jdbc.url=${ORACLE_URL}
quarkus.datasource.username=${ORACLE_USER}
quarkus.datasource.password=${ORACLE_PASSWORD}